# Change the default theme to be use when building the site with Hugo
theme = "hugo-theme-learn"
baseURL = "https://hddkhoa.github.io/AWS-Trainee/"

# Character encoding
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
enableRobotsTXT = true

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
  # Change default color scheme with a variant one. Can be "red", "blue", "green".
  themeVariant = "blue"
  # Git hub repo link
  editURL = "https://github.com/hddkhoa/AWS-Trainee/edit/main/content/"
  description = "RDS Performance Insights & Query Optimization - Comprehensive guide to AWS RDS Performance monitoring and optimization"
  author = "Hà Duy Đăng Khoa - 2180606665"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false
  # Custom CSS
  custom_css = ["css/vietnamese-fix.css"]
  
[Languages]
[Languages.en]
title = "RDS Performance Insights & Query Optimization"
weight = 1
languageName = "English"

[Languages.vi]
title = "RDS Performance Insights & Tối Ưu Hóa Truy Vấn"
weight = 2
languageName = "Tiếng Việt"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "github"
    lineNos = true
    tabWidth = 2
